  version: "3"
  
  services:
    postgis:
      image: 'postgis/postgis:12-master'
      volumes:
        - 'postgis:/var/lib/postgresql/data'
      environment: 
        - POSTGRES_HOST_AUTH_METHOD=trust
  
    app:
      container_name: find_my_coffee_backend
      depends_on:
        - "postgis"
      build: .
      command: bash start.sh
      ports:
        - "3000:3000"
      volumes:
        - .:/coffee
        - app-gems:/app-gems
  
  
  volumes:
    postgis:
    app-gems: